# Inference Evaluation Notebook
This notebook provides an **industry-style evaluation workflow** for inference runs created from either:
- `notebook/inference.ipynb`
- Chainlit UI in `app.py`

## Primary Data Source
This notebook now treats **Phoenix serve** as the primary evaluation store.
Phoenix is the system of record for observability data such as traces, spans, token usage, inputs, outputs, and retrieval telemetry.

## What This Notebook Extracts From Phoenix
The notebook can build multiple dataframes at different granularities:
- **Trace-level dataframe**: one row per trace with token totals and timing
- **Span-level dataframe**: one row per span for low-level debugging
- **Turn-level dataframe**: one row per user-facing turn span
- **LLM dataframe**: one row per LLM-related span with model and token fields
- **Retrieval dataframe**: one row per retrieved document emitted by Phoenix retriever spans

## Important Caveat
Phoenix can only show data that was emitted during the original inference run.
If a field was never sent to Phoenix during inference, it cannot be reconstructed from Phoenix later.

In [1]:
import sys
from pathlib import Path

project_root = Path.cwd().resolve()
if not (project_root / "app.py").exists() and (project_root.parent / "app.py").exists():
    project_root = project_root.parent
    print('project_root: ', project_root)

if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

project_root:  C:\Program Files\Studying\coding\RAG_project

In [2]:
from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import pandas as pd
from phoenix.client import Client

from src.rag.core.observability import (
    DEFAULT_PHOENIX_ENDPOINT,
    DEFAULT_PHOENIX_PROJECT_NAME,
    PHOENIX_INSTALL_COMMAND,
 )


PROJECT_ROOT = project_root
PHOENIX_BASE_URL = DEFAULT_PHOENIX_ENDPOINT
PHOENIX_PROJECT_NAME = DEFAULT_PHOENIX_PROJECT_NAME


@dataclass(frozen=True)
class EvaluationConfig:
    """Configuration object for Phoenix-backed evaluation.

    Purpose:
    - Keep all notebook evaluation settings in one typed object.
    - Make Phoenix endpoint, project name, and query limits explicit and reusable.

    Output:
    - Immutable configuration record used by helper functions below.
    """

    project_root: Path
    phoenix_base_url: str
    phoenix_project_name: str
    phoenix_span_limit: int = 5000
    phoenix_trace_limit: int = 1000


EVAL_CONFIG = EvaluationConfig(
    project_root=PROJECT_ROOT,
    phoenix_base_url=PHOENIX_BASE_URL,
    phoenix_project_name=PHOENIX_PROJECT_NAME,
)


def _safe_json_text(value: Any) -> str:
    """Serialize complex Python objects into stable JSON text for export.

    Purpose:
    - Preserve nested Phoenix attributes in CSV-friendly string form.

    Output:
    - JSON string when serialization succeeds.
    - Fallback string representation when JSON encoding is not possible.
    """
    try:
        return json.dumps(value, ensure_ascii=False, default=str)
    except Exception:
        return str(value)


def _extract_interface(metadata_value: Any) -> str | None:
    """Extract the interface name from Phoenix metadata.

    Purpose:
    - Phoenix metadata is often stored as a nested dictionary.
    - This helper normalizes the `interface` field for reporting.

    Output:
    - Interface label such as `notebook` or `chainlit`.
    - None when no interface information exists.
    """
    if isinstance(metadata_value, dict):
        value = metadata_value.get("interface")
        return str(value) if value is not None else None
    return None


def create_phoenix_client(config: EvaluationConfig) -> Client:
    """Create a Phoenix API client for reading evaluation data from Phoenix serve.

    Purpose:
    - Provide one shared construction point for Phoenix API access.

    Output:
    - Configured `phoenix.client.Client` instance.
    """
    return Client(base_url=config.phoenix_base_url)


def fetch_trace_catalog_dataframe(
    client: Client,
    project_name: str,
    limit: int = 1000,
    session_id: str | None = None,
 ) -> pd.DataFrame:
    """Fetch trace-level summary rows from Phoenix.

    Purpose:
    - Build a compact evaluation view with one row per trace.
    - Expose token totals and timing without requiring manual span inspection.

    Output:
    - DataFrame with trace id, timing, token counts, and optional session id filter applied.
    """
    traces = client.traces.get_traces(
        project_identifier=project_name,
        include_spans=False,
        session_id=session_id,
        limit=limit,
    )

    rows: list[dict[str, Any]] = []
    for trace in traces:
        start_time = pd.to_datetime(trace.get("start_time"), utc=True, errors="coerce")
        end_time = pd.to_datetime(trace.get("end_time"), utc=True, errors="coerce")
        latency_ms = None
        if pd.notna(start_time) and pd.notna(end_time):
            latency_ms = (end_time - start_time).total_seconds() * 1000.0

        rows.append(
            {
                "trace_row_id": trace.get("id"),
                "trace_id": trace.get("trace_id"),
                "project_id": trace.get("project_id"),
                "start_time": start_time,
                "end_time": end_time,
                "latency_ms": latency_ms,
                "token_count_prompt": trace.get("token_count_prompt"),
                "token_count_completion": trace.get("token_count_completion"),
                "token_count_total": trace.get("token_count_total"),
            }
        )

    trace_df = pd.DataFrame(rows)
    if not trace_df.empty:
        trace_df = trace_df.sort_values(by=["start_time"], ascending=False, na_position="last")
    return trace_df.reset_index(drop=True)


def fetch_spans_dataframe(client: Client, project_name: str, limit: int = 5000) -> pd.DataFrame:
    """Fetch raw span data from Phoenix for one project.

    Purpose:
    - Retrieve the detailed observability dataset used to derive all other evaluation tables.

    Output:
    - DataFrame with one row per span and Phoenix-provided attributes as columns.
    """
    spans_df = client.spans.get_spans_dataframe(
        project_name=project_name,
        limit=limit,
    )
    if spans_df.empty:
        return spans_df
    return spans_df.sort_values(by=["start_time"], ascending=False, na_position="last").reset_index(drop=True)


def fetch_available_session_ids(spans_df: pd.DataFrame) -> list[str]:
    """List distinct Phoenix session ids available in the current spans dataset.

    Purpose:
    - Help notebook users choose a valid session id instead of guessing one manually.

    Output:
    - Sorted list of unique session ids present in `attributes.session.id`.
    """
    session_column = "attributes.session.id"
    if spans_df.empty or session_column not in spans_df.columns:
        return []
    return sorted({str(value) for value in spans_df[session_column].dropna().tolist()})


def filter_spans_by_session(spans_df: pd.DataFrame, session_id: str) -> pd.DataFrame:
    """Filter Phoenix spans down to one saved chat session.

    Purpose:
    - Phoenix stores many sessions in one project.
    - This helper isolates the rows related to one `attributes.session.id`.

    Output:
    - DataFrame containing only spans that belong to the requested session id.
    """
    if spans_df.empty or "attributes.session.id" not in spans_df.columns:
        return spans_df.iloc[0:0].copy()

    filtered = spans_df[spans_df["attributes.session.id"] == session_id].copy()
    return filtered.reset_index(drop=True)


def build_span_overview_dataframe(spans_df: pd.DataFrame) -> pd.DataFrame:
    """Create a clean span-level overview for human inspection.

    Purpose:
    - Reduce the very wide Phoenix span table to the most important operational fields.

    Output:
    - DataFrame with one row per span and a curated subset of columns.
    """
    if spans_df.empty:
        return pd.DataFrame()

    overview_df = spans_df.copy()
    overview_df["interface"] = overview_df.get("attributes.metadata", pd.Series([None] * len(overview_df))).apply(_extract_interface)

    selected_columns = [
        "name",
        "span_kind",
        "status_code",
        "start_time",
        "end_time",
        "context.trace_id",
        "context.span_id",
        "parent_id",
        "attributes.session.id",
        "interface",
        "attributes.llm.model_name",
        "attributes.llm.token_count.prompt",
        "attributes.llm.token_count.completion",
        "attributes.llm.token_count.total",
        "attributes.input.value",
        "attributes.output.value",
    ]
    available_columns = [col for col in selected_columns if col in overview_df.columns]
    return overview_df[available_columns].copy()


def build_turn_dataframe_from_phoenix(spans_df: pd.DataFrame) -> pd.DataFrame:
    """Create a turn-level dataframe from Phoenix spans.

    Purpose:
    - Represent one user-facing turn per row using the turn spans emitted by the app or notebook.
    - Support both Chainlit (`rag.chat_turn`) and notebook (`CondensePlusContextChatEngine.chat`) flows.

    Output:
    - DataFrame with one row per detected turn span.
    """
    if spans_df.empty:
        return pd.DataFrame()

    turn_names = {"rag.chat_turn", "CondensePlusContextChatEngine.chat"}
    turn_df = spans_df[spans_df["name"].isin(turn_names)].copy()
    if turn_df.empty:
        return turn_df

    turn_df["interface"] = turn_df.get("attributes.metadata", pd.Series([None] * len(turn_df))).apply(_extract_interface)
    selected_columns = [
        "name",
        "start_time",
        "end_time",
        "status_code",
        "context.trace_id",
        "context.span_id",
        "attributes.session.id",
        "interface",
        "attributes.input.value",
        "attributes.output.value",
        "attributes.llm.token_count.prompt",
        "attributes.llm.token_count.completion",
        "attributes.llm.token_count.total",
    ]
    available_columns = [col for col in selected_columns if col in turn_df.columns]
    return turn_df[available_columns].sort_values(by=["start_time"], ascending=True, na_position="last").reset_index(drop=True)


def build_llm_dataframe_from_phoenix(spans_df: pd.DataFrame) -> pd.DataFrame:
    """Create an LLM-call dataframe from Phoenix spans.

    Purpose:
    - Isolate spans that contain model-level metadata or token accounting.
    - Make model usage and token analysis easy to export and audit.

    Output:
    - DataFrame with one row per LLM-related span.
    """
    if spans_df.empty:
        return pd.DataFrame()

    llm_mask = spans_df.get("attributes.llm.model_name", pd.Series([None] * len(spans_df))).notna()
    llm_mask = llm_mask | spans_df.get("attributes.llm.token_count.total", pd.Series([None] * len(spans_df))).notna()
    llm_df = spans_df[llm_mask].copy()
    if llm_df.empty:
        return llm_df

    llm_df["interface"] = llm_df.get("attributes.metadata", pd.Series([None] * len(llm_df))).apply(_extract_interface)
    selected_columns = [
        "name",
        "start_time",
        "end_time",
        "status_code",
        "context.trace_id",
        "context.span_id",
        "attributes.session.id",
        "interface",
        "attributes.llm.model_name",
        "attributes.llm.input_messages",
        "attributes.llm.output_messages",
        "attributes.llm.invocation_parameters",
        "attributes.llm.token_count.prompt",
        "attributes.llm.token_count.completion",
        "attributes.llm.token_count.total",
        "attributes.output.value",
    ]
    available_columns = [col for col in selected_columns if col in llm_df.columns]
    return llm_df[available_columns].sort_values(by=["start_time"], ascending=True, na_position="last").reset_index(drop=True)


def build_retrieval_dataframe_from_phoenix(spans_df: pd.DataFrame) -> pd.DataFrame:
    """Explode Phoenix retriever spans into one row per retrieved document.

    Purpose:
    - Phoenix retriever spans can contain an `attributes.retrieval.documents` list.
    - This helper normalizes those nested document records into a flat evaluation table.

    Output:
    - DataFrame with one row per retrieved document.
    """
    retrieval_column = "attributes.retrieval.documents"
    if spans_df.empty or retrieval_column not in spans_df.columns:
        return pd.DataFrame()

    retrieval_spans = spans_df[spans_df[retrieval_column].notna()].copy()
    rows: list[dict[str, Any]] = []

    for _, span_row in retrieval_spans.iterrows():
        documents = span_row.get(retrieval_column) or []
        if not isinstance(documents, list):
            continue

        for rank, document in enumerate(documents, start=1):
            if not isinstance(document, dict):
                continue

            rows.append(
                {
                    "trace_id": span_row.get("context.trace_id"),
                    "span_id": span_row.get("context.span_id"),
                    "retrieval_span_name": span_row.get("name"),
                    "session_id": span_row.get("attributes.session.id"),
                    "query_text": span_row.get("attributes.input.value"),
                    "document_rank": rank,
                    "document_score": document.get("document.score"),
                    "document_content_preview": (document.get("document.content") or "")[:500],
                    "document_raw": _safe_json_text(document),
                }
            )

    retrieval_df = pd.DataFrame(rows)
    if not retrieval_df.empty:
        retrieval_df = retrieval_df.sort_values(by=["trace_id", "document_rank"], ascending=[True, True], na_position="last")
    return retrieval_df.reset_index(drop=True)


phoenix_client = create_phoenix_client(EVAL_CONFIG)
catalog_df = fetch_trace_catalog_dataframe(
    client=phoenix_client,
    project_name=EVAL_CONFIG.phoenix_project_name,
    limit=EVAL_CONFIG.phoenix_trace_limit,
)
all_project_spans_df = fetch_spans_dataframe(
    client=phoenix_client,
    project_name=EVAL_CONFIG.phoenix_project_name,
    limit=EVAL_CONFIG.phoenix_span_limit,
)
available_session_ids = fetch_available_session_ids(all_project_spans_df)

print(f"Phoenix endpoint: {EVAL_CONFIG.phoenix_base_url}")
print(f"Phoenix project:  {EVAL_CONFIG.phoenix_project_name}")
print(f"Install command if Phoenix packages are missing: {PHOENIX_INSTALL_COMMAND}")
print(f"Detected traces in catalog: {len(catalog_df)}")
print(f"Available Phoenix session ids: {available_session_ids[:10]}")
catalog_df.head(20)

c:\Users\jason\miniconda3\envs\ai\Lib\site-packages\authlib\_joserfc_helpers.py:8: AuthlibDeprecationWarning: authlib.jose module is deprecated, please use joserfc instead.
It will be compatible before version 2.0.0.
  from authlib.jose import ECKey

Phoenix endpoint: http://localhost:6006
Phoenix project:  rag-news-chatbot
Install command if Phoenix packages are missing: pip install arize-phoenix arize-phoenix-otel openinference-instrumentation-llama-index
Detected traces in catalog: 31
Available Phoenix session ids: ['Donald_Trump', 'Test_Chat_session', 'chat_20260701_223412', 'chat_20260701_230551', 'chat_20260701_231246']

,trace_row_id,trace_id,project_id,start_time,end_time,latency_ms,token_count_prompt,token_count_completion,token_count_total
0,VHJhY2U6NjI=,6b23922c698c812d440d85b8c5d9e766,UHJvamVjdDo0,2026-07-10 05:28:45.010993+00:00,2026-07-10 05:29:56.126233+00:00,71115.240,7503,300,7803
1,VHJhY2U6NTY=,25e1fa6a8dd8f9d7b8cd65e777aaf6da,UHJvamVjdDo0,2026-07-06 06:46:35.894681+00:00,2026-07-06 06:47:47.799154+00:00,71904.473,7017,284,7301
2,VHJhY2U6NTU=,3d38d313b4cfaa5abb911e2c051850a4,UHJvamVjdDo0,2026-07-06 06:44:55.329681+00:00,2026-07-06 06:46:06.377400+00:00,71047.719,6887,121,7008
3,VHJhY2U6NTQ=,a675b3a81576d7d789aeed587f4b217e,UHJvamVjdDo0,2026-07-06 06:30:20.036784+00:00,2026-07-06 06:31:20.962444+00:00,60925.660,5533,191,5724
4,VHJhY2U6NTM=,aa761f0791e762e4a6696c1b7734632f,UHJvamVjdDo0,2026-07-06 06:23:06.454026+00:00,2026-07-06 06:24:03.668721+00:00,57214.695,4676,127,4803
5,VHJhY2U6NDc=,3fef4a593df9d75ab1876de6a7f83e26,UHJvamVjdDo0,2026-07-06 03:13:45.062124+00:00,2026-07-06 03:15:00.861398+00:00,75799.274,4062,339,4401
6,VHJhY2U6NDY=,a4d0a915da73b872bea0f403480ee9c7,UHJvamVjdDo0,2026-07-06 03:11:20.006984+00:00,2026-07-06 03:11:59.023908+00:00,39016.924,2581,248,2829
7,VHJhY2U6NDA=,82b56138ab46c2ba0b0a1d516f10bb39,UHJvamVjdDo0,2026-07-01 15:12:46.078460+00:00,2026-07-01 15:13:46.047206+00:00,59968.746,3950,30,3980
8,VHJhY2U6Mzk=,f6643cf69502338c2f8c768a15d1e4c8,UHJvamVjdDo0,2026-07-01 15:09:10.424399+00:00,2026-07-01 15:10:30.676882+00:00,80252.483,4688,368,5056
9,VHJhY2U6Mzg=,d86fb67cd624e2fec720109f9af4cdfd,UHJvamVjdDo0,2026-07-01 15:07:30.133315+00:00,2026-07-01 15:08:28.780206+00:00,58646.891,3659,220,3879
10,VHJhY2U6Mzc=,fa677a0a73a6a54088e7046ebdc41070,UHJvamVjdDo0,2026-07-01 15:05:55.612485+00:00,2026-07-01 15:06:50.206652+00:00,54594.167,3929,10,3939
11,VHJhY2U6MzY=,f2048d477a8fb25393ed99cbace9b374,UHJvamVjdDo0,2026-07-01 14:41:51.626769+00:00,2026-07-01 14:43:22.088507+00:00,90461.738,4086,651,4737
12,VHJhY2U6MzU=,83ecdd3aeb5c4e74568b02afe8410f26,UHJvamVjdDo0,2026-07-01 14:34:34.386912+00:00,2026-07-01 14:35:47.425719+00:00,73038.807,3977,175,4152
13,VHJhY2U6MzQ=,f0aa2aa02b3f97a15b0fa0df2828d40c,UHJvamVjdDo0,2026-07-01 14:30:38.183347+00:00,2026-07-01 14:33:26.190100+00:00,168006.753,13093,590,13683
14,VHJhY2U6MzM=,d22ca5fecd6107dadbf7f3efc18f9360,UHJvamVjdDo0,2026-07-01 11:54:30.660439+00:00,2026-07-01 11:56:34.059492+00:00,123399.053,12439,833,13272
15,VHJhY2U6MzI=,f3d9a2e5aa72fedc29139ec8db64f23a,UHJvamVjdDo0,2026-07-01 10:58:06.481094+00:00,2026-07-01 11:00:13.791548+00:00,127310.454,12365,666,13031
16,VHJhY2U6MzE=,940d711bd844e9c67e88f8ad1f6e9c88,UHJvamVjdDo0,2026-07-01 10:55:53.179782+00:00,2026-07-01 10:56:48.452443+00:00,55272.661,4119,123,4242
17,VHJhY2U6MzA=,f3ea842d883a474fd5e8111c901d7634,UHJvamVjdDo0,2026-07-01 10:49:18.945317+00:00,2026-07-01 10:50:56.255361+00:00,97310.044,11971,503,12474
18,VHJhY2U6Mjk=,49e7a630bfb87d197d62357938510e8e,UHJvamVjdDo0,2026-07-01 10:47:59.838388+00:00,2026-07-01 10:48:48.982001+00:00,49143.613,4119,121,4240
19,VHJhY2U6Mjg=,4b62ed0817cde49391b68aaa0f5d0d42,UHJvamVjdDo0,2026-07-01 08:58:47.214192+00:00,2026-07-01 09:00:43.890761+00:00,116676.569,12309,604,12913

In [3]:
# --- Example usage: pick one Phoenix session id, then run this cell ---

# For this project, the Phoenix session id usually matches the saved chat id used during inference.
TARGET_SESSION_ID = available_session_ids[0] if "available_session_ids" in globals() and available_session_ids else None


def get_phoenix_evaluation_bundle(
    session_id: str,
    config: EvaluationConfig,
 ) -> dict[str, pd.DataFrame]:
    """Build the full evaluation bundle directly from Phoenix serve.

    Purpose:
    - Use Phoenix as the single source of evaluation truth for the selected session.
    - Return multiple dataframes because Phoenix data exists at several granularities: traces, spans,
      turn spans, LLM spans, and retrieved documents.

    Output:
    - Dictionary containing the following dataframes:
      `trace_df`, `session_spans_df`, `span_overview_df`, `turn_df`, `llm_df`, and `retrieval_df`.
    """
    client = create_phoenix_client(config)

    trace_df = fetch_trace_catalog_dataframe(
        client=client,
        project_name=config.phoenix_project_name,
        limit=config.phoenix_trace_limit,
        session_id=session_id,
    )

    all_spans_df = fetch_spans_dataframe(
        client=client,
        project_name=config.phoenix_project_name,
        limit=config.phoenix_span_limit,
    )

    session_spans_df = filter_spans_by_session(all_spans_df, session_id=session_id)
    span_overview_df = build_span_overview_dataframe(session_spans_df)
    turn_df = build_turn_dataframe_from_phoenix(session_spans_df)
    llm_df = build_llm_dataframe_from_phoenix(session_spans_df)
    retrieval_df = build_retrieval_dataframe_from_phoenix(session_spans_df)

    return {
        "trace_df": trace_df,
        "session_spans_df": session_spans_df,
        "span_overview_df": span_overview_df,
        "turn_df": turn_df,
        "llm_df": llm_df,
        "retrieval_df": retrieval_df,
    }


def save_phoenix_evaluation_outputs(
    session_id: str,
    project_root: Path,
    phoenix_bundle: dict[str, pd.DataFrame],
 ) -> Path:
    """Persist Phoenix evaluation dataframes as CSV files.

    Purpose:
    - Export notebook evaluation artifacts into files that can be audited or shared.

    Output:
    - Path to the output directory containing the generated CSV files.
    """
    output_dir = project_root / "result" / "evaluation_outputs"
    output_dir.mkdir(parents=True, exist_ok=True)

    for dataframe_name, dataframe in phoenix_bundle.items():
        dataframe.to_csv(
            output_dir / f"{session_id}_{dataframe_name}.csv",
            index=False,
            encoding="utf-8",
        )

    return output_dir


if not TARGET_SESSION_ID:
    print("No Phoenix session ids were found. Run traced inference first, then rerun Cell 3.")
else:
    phoenix_bundle = get_phoenix_evaluation_bundle(
        session_id=TARGET_SESSION_ID,
        config=EVAL_CONFIG,
    )

    trace_df = phoenix_bundle["trace_df"]
    session_spans_df = phoenix_bundle["session_spans_df"]
    span_overview_df = phoenix_bundle["span_overview_df"]
    turn_df = phoenix_bundle["turn_df"]
    llm_df = phoenix_bundle["llm_df"]
    retrieval_df = phoenix_bundle["retrieval_df"]

    print("=== Phoenix Evaluation Context ===")
    print(f"Phoenix endpoint: {EVAL_CONFIG.phoenix_base_url}")
    print(f"Phoenix project:  {EVAL_CONFIG.phoenix_project_name}")
    print(f"Session id:       {TARGET_SESSION_ID}")
    print(f"Trace rows:       {len(trace_df)}")
    print(f"Span rows:        {len(session_spans_df)}")
    print(f"Turn rows:        {len(turn_df)}")
    print(f"LLM rows:         {len(llm_df)}")
    print(f"Retrieval rows:   {len(retrieval_df)}")

    print("\n=== Trace DataFrame ===")
    display(trace_df.head(20))

    print("\n=== Span Overview DataFrame ===")
    display(span_overview_df.head(20))

    print("\n=== Turn DataFrame ===")
    display(turn_df.head(20))

    print("\n=== LLM DataFrame ===")
    display(llm_df.head(20))

    print("\n=== Retrieval DataFrame ===")
    display(retrieval_df.head(30))

    output_dir = save_phoenix_evaluation_outputs(
        session_id=TARGET_SESSION_ID,
        project_root=PROJECT_ROOT,
        phoenix_bundle=phoenix_bundle,
    )
    print(f"Saved Phoenix evaluation CSV files to: {output_dir}")

=== Phoenix Evaluation Context ===
Phoenix endpoint: http://localhost:6006
Phoenix project:  rag-news-chatbot
Session id:       Donald_Trump
Trace rows:       12
Span rows:        218
Turn rows:        16
LLM rows:         44
Retrieval rows:   275

=== Trace DataFrame ===

,trace_row_id,trace_id,project_id,start_time,end_time,latency_ms,token_count_prompt,token_count_completion,token_count_total
0,VHJhY2U6MzQ=,f0aa2aa02b3f97a15b0fa0df2828d40c,UHJvamVjdDo0,2026-07-01 14:30:38.183347+00:00,2026-07-01 14:33:26.190100+00:00,168006.753,13093,590,13683
1,VHJhY2U6MzM=,d22ca5fecd6107dadbf7f3efc18f9360,UHJvamVjdDo0,2026-07-01 11:54:30.660439+00:00,2026-07-01 11:56:34.059492+00:00,123399.053,12439,833,13272
2,VHJhY2U6MzI=,f3d9a2e5aa72fedc29139ec8db64f23a,UHJvamVjdDo0,2026-07-01 10:58:06.481094+00:00,2026-07-01 11:00:13.791548+00:00,127310.454,12365,666,13031
3,VHJhY2U6MzA=,f3ea842d883a474fd5e8111c901d7634,UHJvamVjdDo0,2026-07-01 10:49:18.945317+00:00,2026-07-01 10:50:56.255361+00:00,97310.044,11971,503,12474
4,VHJhY2U6Mjg=,4b62ed0817cde49391b68aaa0f5d0d42,UHJvamVjdDo0,2026-07-01 08:58:47.214192+00:00,2026-07-01 09:00:43.890761+00:00,116676.569,12309,604,12913
5,VHJhY2U6MTc=,9b5395c6ccf40bd0405defcf737ab0f0,UHJvamVjdDo0,2026-07-01 04:23:23.881876+00:00,2026-07-01 04:24:50.978162+00:00,87096.286,9341,617,9958
6,VHJhY2U6MTY=,a27cc11ec7d5d43baf7292a1a7fd19a2,UHJvamVjdDo0,2026-07-01 04:19:01.846737+00:00,2026-07-01 04:20:18.228971+00:00,76382.234,7688,499,8187
7,VHJhY2U6MTU=,6fbae27a86ec3f22f0c08834fcdbb38b,UHJvamVjdDo0,2026-07-01 04:16:39.900245+00:00,2026-07-01 04:17:57.592931+00:00,77692.686,4345,408,4753
8,VHJhY2U6MTQ=,fbb1d06fc54a882ed06afdf2986d9f4d,UHJvamVjdDo0,2026-06-30 17:42:52.331695+00:00,2026-06-30 17:43:49.239148+00:00,56907.453,5571,384,5955
9,VHJhY2U6MTM=,80eb72ab82e62354bc7969f3776c6b51,UHJvamVjdDo0,2026-06-30 17:21:58.744191+00:00,2026-06-30 17:22:48.801666+00:00,50057.475,5128,363,5491
10,VHJhY2U6MTI=,12e34b0e14146ab58e9959ba8705c111,UHJvamVjdDo0,2026-06-30 17:21:18.488193+00:00,2026-06-30 17:21:58.706920+00:00,40218.727,4743,88,4831
11,VHJhY2U6MTE=,7154de4aac75a7442dd6b378a732b535,UHJvamVjdDo0,2026-06-30 17:20:39.999772+00:00,2026-06-30 17:21:18.449741+00:00,38449.969,3258,182,3440

=== Span Overview DataFrame ===

,name,span_kind,status_code,start_time,end_time,context.trace_id,context.span_id,parent_id,attributes.session.id,interface,attributes.llm.model_name,attributes.llm.token_count.prompt,attributes.llm.token_count.completion,attributes.llm.token_count.total,attributes.input.value,attributes.output.value
0,Ollama.chat,LLM,OK,2026-07-01 14:31:36.001830+00:00,2026-07-01 14:33:24.106008+00:00,f0aa2aa02b3f97a15b0fa0df2828d40c,dc53047d4d707bc0,f12554dba6b418f0,Donald_Trump,chainlit,gemma3:1b,6587.0,526.0,7113.0,"{""messages"": [""ChatMessage(role=<MessageRole.S...",assistant: You’ve articulated a very important...
1,Ollama.predict,LLM,OK,2026-07-01 14:31:35.998692+00:00,2026-07-01 14:33:26.154738+00:00,f0aa2aa02b3f97a15b0fa0df2828d40c,f12554dba6b418f0,b4dbb817a1788462,Donald_Trump,chainlit,gemma3:1b,NaN,NaN,NaN,"{""prompt"": ""ChatPromptTemplate(metadata={'prom...",You’ve articulated a very important and nuance...
2,DefaultRefineProgram.__call__,CHAIN,OK,2026-07-01 14:31:35.997571+00:00,2026-07-01 14:33:26.160993+00:00,f0aa2aa02b3f97a15b0fa0df2828d40c,b4dbb817a1788462,d4b48245fdaa0fda,Donald_Trump,chainlit,NaN,NaN,NaN,NaN,"{""kwds"": {""context_str"": ""source_folder: hk_fr...","{""query_satisfied"":true,""answer"":""You’ve artic..."
3,TokenTextSplitter.split_text,CHAIN,OK,2026-07-01 14:31:35.985524+00:00,2026-07-01 14:31:35.990348+00:00,f0aa2aa02b3f97a15b0fa0df2828d40c,271c4f74dd721619,d4b48245fdaa0fda,Donald_Trump,chainlit,NaN,NaN,NaN,NaN,"{""text"": ""source_folder: hk_free_press_news\nf...","[""source_folder: hk_free_press_news\nfile_path..."
4,CompactAndRefine.get_response,CHAIN,OK,2026-07-01 14:31:35.978265+00:00,2026-07-01 14:33:26.165850+00:00,f0aa2aa02b3f97a15b0fa0df2828d40c,d4b48245fdaa0fda,5504286d04446040,Donald_Trump,chainlit,NaN,NaN,NaN,NaN,Trump rather than Bannon hate Joe Biden,You’ve articulated a very important and nuance...
5,TokenTextSplitter.split_text,CHAIN,OK,2026-07-01 14:31:35.963101+00:00,2026-07-01 14:31:35.970976+00:00,f0aa2aa02b3f97a15b0fa0df2828d40c,4f76451717aa68de,5504286d04446040,Donald_Trump,chainlit,NaN,NaN,NaN,NaN,"{""text"": ""source_folder: hk_free_press_news\nf...","[""source_folder: hk_free_press_news\nfile_path..."
6,CompactAndRefine.get_response,CHAIN,OK,2026-07-01 14:31:35.949847+00:00,2026-07-01 14:33:26.170729+00:00,f0aa2aa02b3f97a15b0fa0df2828d40c,5504286d04446040,cc4029197a9e64c7,Donald_Trump,chainlit,NaN,NaN,NaN,NaN,"{""query_str"": ""Trump rather than Bannon hate J...",You’ve articulated a very important and nuance...
7,CompactAndRefine.synthesize,CHAIN,OK,2026-07-01 14:31:35.948512+00:00,2026-07-01 14:33:26.175640+00:00,f0aa2aa02b3f97a15b0fa0df2828d40c,cc4029197a9e64c7,7d53ab57a4218d82,Donald_Trump,chainlit,NaN,NaN,NaN,NaN,Trump rather than Bannon hate Joe Biden,You’ve articulated a very important and nuance...
8,BM25Retriever._retrieve,RETRIEVER,OK,2026-07-01 14:31:35.905769+00:00,2026-07-01 14:31:35.914591+00:00,f0aa2aa02b3f97a15b0fa0df2828d40c,64a2fd71e019e610,7666e5855d17a3a1,Donald_Trump,chainlit,NaN,NaN,NaN,NaN,"{""query_bundle"": {""query_str"": ""**Why did Step...","[""<NodeWithScore(node=TextNode(id_=fb9a6140-2c..."
9,BM25Retriever.retrieve,RETRIEVER,OK,2026-07-01 14:31:35.900393+00:00,2026-07-01 14:31:35.923556+00:00,f0aa2aa02b3f97a15b0fa0df2828d40c,7666e5855d17a3a1,564d8a94509ce54f,Donald_Trump,chainlit,NaN,NaN,NaN,NaN,**Why did Stephen Bannon consistently criticiz...,"[""<NodeWithScore(node=TextNode(id_=fb9a6140-2c..."
10,HuggingFaceEmbedding._get_query_embedding,EMBEDDING,OK,2026-07-01 14:31:35.383396+00:00,2026-07-01 14:31:35.827220+00:00,f0aa2aa02b3f97a15b0fa0df2828d40c,9f4b4c68a275b464,7c8ff9ba090e6428,Donald_Trump,chainlit,NaN,NaN,NaN,NaN,"{""query"": ""**Why did Stephen Bannon consistent...",NaN
11,HuggingFaceEmbedding.get_query_embedding,EMBEDDING,OK,2026-07-01 14:31:35.382271+00:00,2026-07-01 14:31:35.834069+00:00,f0aa2aa02b3f97a15b0fa0df2828d40c,7c8ff9ba090e6428,dddef252ac7962ee,Donald_Trump,chainlit,NaN,NaN,NaN,NaN,"{""query"": ""**Why did Stephen Bannon consistent...",NaN
12,VectorIndexRetriever._retrieve,RETRIEVER,OK,2026-07-01 14:31:35.381771+00:00,2026-07-01 14:31:35.875051+00:00,f0aa2aa02b3f97a15b0fa0df2828d40c,dddef252ac7962ee,ab27290ed3da5e61,Donald_Trump,chainlit,NaN,NaN,NaN,NaN,"{""query_bundle"": {""query_str"": ""**Why did Step...","[""<NodeWithScore(node=TextNode(id_=f422caab-9b..."
13,VectorIndexRetriever.retrieve,RETRIEVER,OK,2026-07-01 14:31:35.380889+00:00,2026-07-01 14:31:35.888330+00:00,f0aa2aa02b3f97a15b0fa0df2828d40c,ab27290ed3da5e61,564d8a94509ce54f,Donald_Trump,chainlit,NaN,NaN,NaN,NaN,**Why did Stephen Bannon consistently criticiz...,"[""<NodeWithScore(node=TextNode(id_=f422caab-9b..."
14,HybridRetriever._retrieve,RETRIEVER,OK,2026-07-01 14:31:35.380449+00:00,2026-07-01 14:31:35.933497+00:00,f0aa2aa02b3f97a15b0fa0df2828d40c,564d8a94509ce54f,10ef4a19cc1f0299,Donald_Trump,chainlit,NaN,NaN,NaN,NaN,"{""query_bundle"": {""query_str"": ""**Why did Step...","[""<NodeWithScore(node=TextNode(id_=f422caab-9b..."
15,HybridRetriever.retrieve,RETRIEVER,OK,2026-07-01 14:31:35.379703+00:00,2026-07-01 14:31:35.940714+00:00,f0aa2aa02b3f97a15b0fa0df2828d40c,10ef4a19cc1f0299,7d53ab57a4218d82,Donald_Trump,chainlit,NaN,NaN,NaN,NaN,**Why did Stephen Bannon consistently criticiz...,"[""<NodeWithScore(node=TextNode(id_=f422caab-9b..."
16,Ollama.chat,LLM,OK,2026-07-01 14:30:39.231089+00:00,2026-07-01 14:31:33.344069+00:00,f0aa2aa02b3f97a15b0fa0df2828d40c,f4447d4fee7bce30,d13cec514da1ca22,Donald_Trump,chainlit,gemma3:1b,3253.0,32.0,3285.0,"{""messages"": [""ChatMessage(role=<MessageRole.U...",assistant: **Why did Stephen Bannon consistent...
17,Ollama.complete,LLM,OK,2026-07-01 14:30:38.217924+00:00,2026-07-01 14:31:35.373954+00:00,f0aa2aa02b3f97a15b0fa0df2828d40c,d13cec514da1ca22,7d53ab57a4218d82,Donald_Trump,chainlit,gemma3:1b,3253.0,32.0,3285.0,"{""args"": [""\n Given the following conversatio...",**Why did Stephen Bannon consistently criticiz...
18,CondensePlusContextChatEngine.chat,CHAIN,OK,2026-07-01 14:30:38.184207+00:00,2026-07-01 14:33:26.181544+00:00,f0aa2aa02b3f97a15b0fa0df2828d40c,7d53ab57a4218d82,b176e80bc9d808b7,Donald_Trump,chainlit,NaN,NaN,NaN,NaN,"{""message"": ""Trump rather than Bannon hate Joe...","{""response"": ""You’ve articulated a very import..."
19,rag.chat_turn,CHAIN,OK,2026-07-01 14:30:38.183347+00:00,2026-07-01 14:33:26.190100+00:00,f0aa2aa02b3f97a15b0fa0df2828d40c,b176e80bc9d808b7,NaN,Donald_Trump,chainlit,NaN,NaN,NaN,NaN,"{""message"": ""Trump rather than Bannon hate Joe...","{""response"": ""You’ve articulated a very import..."

=== Turn DataFrame ===

,name,start_time,end_time,status_code,context.trace_id,context.span_id,attributes.session.id,interface,attributes.input.value,attributes.output.value,attributes.llm.token_count.prompt,attributes.llm.token_count.completion,attributes.llm.token_count.total
0,CondensePlusContextChatEngine.chat,2026-06-30 17:20:39.999772+00:00,2026-06-30 17:21:18.449741+00:00,OK,7154de4aac75a7442dd6b378a732b535,bc6c7019015b9e77,Donald_Trump,notebook,"{""message"": ""Who is donald trump ?""}","{""response"": ""Donald Trump is an American busi...",NaN,NaN,NaN
1,CondensePlusContextChatEngine.chat,2026-06-30 17:21:18.488193+00:00,2026-06-30 17:21:58.706920+00:00,OK,12e34b0e14146ab58e9959ba8705c111,77ea5dd6d2d74a8c,Donald_Trump,notebook,"{""message"": ""Did he met with Xi ?""}","{""response"": ""Yes, Donald Trump did meet with ...",NaN,NaN,NaN
2,CondensePlusContextChatEngine.chat,2026-06-30 17:21:58.744191+00:00,2026-06-30 17:22:48.801666+00:00,OK,80eb72ab82e62354bc7969f3776c6b51,da2885ce630964f0,Donald_Trump,notebook,"{""message"": ""What is the relationship between ...","{""response"": ""The relationship between Donald ...",NaN,NaN,NaN
3,rag.chat_turn,2026-06-30 17:42:52.331695+00:00,2026-06-30 17:43:49.239148+00:00,OK,fbb1d06fc54a882ed06afdf2986d9f4d,0c5dd4b4b28ef725,Donald_Trump,chainlit,"{""message"": ""are they very good friend ?""}","{""response"": ""That’s a really interesting and ...",NaN,NaN,NaN
4,CondensePlusContextChatEngine.chat,2026-06-30 17:42:52.332347+00:00,2026-06-30 17:43:49.232418+00:00,OK,fbb1d06fc54a882ed06afdf2986d9f4d,9f79c8a8365e183b,Donald_Trump,chainlit,"{""message"": ""are they very good friend ?""}","{""response"": ""That’s a really interesting and ...",NaN,NaN,NaN
5,CondensePlusContextChatEngine.chat,2026-07-01 04:16:39.900245+00:00,2026-07-01 04:17:57.592931+00:00,OK,6fbae27a86ec3f22f0c08834fcdbb38b,1b8c261c9cca46ac,Donald_Trump,notebook,"{""message"": ""Did Stephen Kevin Steve Bannon ha...","{""response"": ""That’s a really perceptive quest...",NaN,NaN,NaN
6,CondensePlusContextChatEngine.chat,2026-07-01 04:19:01.846737+00:00,2026-07-01 04:20:18.228971+00:00,OK,a27cc11ec7d5d43baf7292a1a7fd19a2,a1f8e5603ed6bf8c,Donald_Trump,notebook,"{""message"": ""Did Stephen Kevin Steve Bannon ha...","{""response"": ""Okay, let’s delve into the quest...",NaN,NaN,NaN
7,rag.chat_turn,2026-07-01 04:23:23.881876+00:00,2026-07-01 04:24:50.978162+00:00,OK,9b5395c6ccf40bd0405defcf737ab0f0,278d6311eecd10bc,Donald_Trump,chainlit,"{""message"": ""Does Xi hate Stephen Kevin Steve ...","{""response"": ""That’s a really interesting and ...",NaN,NaN,NaN
8,CondensePlusContextChatEngine.chat,2026-07-01 04:23:23.882401+00:00,2026-07-01 04:24:50.972430+00:00,OK,9b5395c6ccf40bd0405defcf737ab0f0,9b55d1d6d04f5501,Donald_Trump,chainlit,"{""message"": ""Does Xi hate Stephen Kevin Steve ...","{""response"": ""That’s a really interesting and ...",NaN,NaN,NaN
9,CondensePlusContextChatEngine.chat,2026-07-01 08:58:47.214192+00:00,2026-07-01 09:00:43.890761+00:00,OK,4b62ed0817cde49391b68aaa0f5d0d42,9afa710ef87d0d0b,Donald_Trump,notebook,"{""message"": ""What are the characteristics of T...","{""response"": ""Stephen Trump is a remarkably co...",NaN,NaN,NaN
10,CondensePlusContextChatEngine.chat,2026-07-01 10:49:18.945317+00:00,2026-07-01 10:50:56.255361+00:00,OK,f3ea842d883a474fd5e8111c901d7634,2fb31777f3f480c5,Donald_Trump,notebook,"{""message"": ""Did Trump mention Japanese yen cr...","{""response"": ""Yes, absolutely. Stephen Bannon ...",NaN,NaN,NaN
11,CondensePlusContextChatEngine.chat,2026-07-01 10:58:06.481094+00:00,2026-07-01 11:00:13.791548+00:00,OK,f3d9a2e5aa72fedc29139ec8db64f23a,aeb19fd9634a8a47,Donald_Trump,notebook,"{""message"": ""Did Trump mention CCCP ?""}","{""response"": ""Yes, Stephen Bannon did mention ...",NaN,NaN,NaN
12,rag.chat_turn,2026-07-01 11:54:30.660439+00:00,2026-07-01 11:56:34.059492+00:00,OK,d22ca5fecd6107dadbf7f3efc18f9360,d1bf98cabb260a40,Donald_Trump,chainlit,"{""message"": ""Why Trump hate Joe Biden so much ?""}","{""response"": ""Stephen Bannon’s animosity towar...",NaN,NaN,NaN
13,CondensePlusContextChatEngine.chat,2026-07-01 11:54:30.661107+00:00,2026-07-01 11:56:34.053324+00:00,OK,d22ca5fecd6107dadbf7f3efc18f9360,0d9ba39c01cb7ecc,Donald_Trump,chainlit,"{""message"": ""Why Trump hate Joe Biden so much ?""}","{""response"": ""Stephen Bannon’s animosity towar...",NaN,NaN,NaN
14,rag.chat_turn,2026-07-01 14:30:38.183347+00:00,2026-07-01 14:33:26.190100+00:00,OK,f0aa2aa02b3f97a15b0fa0df2828d40c,b176e80bc9d808b7,Donald_Trump,chainlit,"{""message"": ""Trump rather than Bannon hate Joe...","{""response"": ""You’ve articulated a very import...",NaN,NaN,NaN
15,CondensePlusContextChatEngine.chat,2026-07-01 14:30:38.184207+00:00,2026-07-01 14:33:26.181544+00:00,OK,f0aa2aa02b3f97a15b0fa0df2828d40c,7d53ab57a4218d82,Donald_Trump,chainlit,"{""message"": ""Trump rather than Bannon hate Joe...","{""response"": ""You’ve articulated a very import...",NaN,NaN,NaN

=== LLM DataFrame ===

,name,start_time,end_time,status_code,context.trace_id,context.span_id,attributes.session.id,interface,attributes.llm.model_name,attributes.llm.input_messages,attributes.llm.output_messages,attributes.llm.invocation_parameters,attributes.llm.token_count.prompt,attributes.llm.token_count.completion,attributes.llm.token_count.total,attributes.output.value
0,Ollama.predict,2026-06-30 17:20:42.494305+00:00,2026-06-30 17:21:18.445003+00:00,OK,7154de4aac75a7442dd6b378a732b535,e756439b203a8b90,Donald_Trump,notebook,gemma3:1b,None,None,"{""context_window"":32768,""num_output"":256,""is_c...",NaN,NaN,NaN,Donald Trump is an American businessman and po...
1,Ollama.chat,2026-06-30 17:20:42.496050+00:00,2026-06-30 17:21:18.444573+00:00,OK,7154de4aac75a7442dd6b378a732b535,83bef5bb95fb03d4,Donald_Trump,notebook,gemma3:1b,[{'message.content': ' The following is a fr...,[{'message.content': 'Donald Trump is an Ameri...,"{""context_window"":32768,""num_output"":256,""is_c...",3258.0,182.0,3440.0,assistant: Donald Trump is an American busines...
2,Ollama.complete,2026-06-30 17:21:18.491248+00:00,2026-06-30 17:21:21.069975+00:00,OK,12e34b0e14146ab58e9959ba8705c111,37596af57b6491f4,Donald_Trump,notebook,gemma3:1b,None,None,"{""context_window"":32768,""num_output"":256,""is_c...",259.0,9.0,268.0,Did Donald Trump meet with Xi Jinping?
3,Ollama.chat,2026-06-30 17:21:18.493967+00:00,2026-06-30 17:21:21.069446+00:00,OK,12e34b0e14146ab58e9959ba8705c111,cdd3799bb4452909,Donald_Trump,notebook,gemma3:1b,[{'message.content': ' Given the following c...,[{'message.content': 'Did Donald Trump meet wi...,"{""context_window"":32768,""num_output"":256,""is_c...",259.0,9.0,268.0,assistant: Did Donald Trump meet with Xi Jinping?
4,Ollama.predict,2026-06-30 17:21:21.218562+00:00,2026-06-30 17:21:58.702976+00:00,OK,12e34b0e14146ab58e9959ba8705c111,21c9b5d54f8616ce,Donald_Trump,notebook,gemma3:1b,None,None,"{""context_window"":32768,""num_output"":256,""is_c...",NaN,NaN,NaN,"Yes, Donald Trump did meet with Xi Jinping, th..."
5,Ollama.chat,2026-06-30 17:21:21.221354+00:00,2026-06-30 17:21:58.702604+00:00,OK,12e34b0e14146ab58e9959ba8705c111,d06ff0f37c527e21,Donald_Trump,notebook,gemma3:1b,[{'message.content': ' The following is a fr...,"[{'message.content': 'Yes, Donald Trump did me...","{""context_window"":32768,""num_output"":256,""is_c...",4225.0,70.0,4295.0,"assistant: Yes, Donald Trump did meet with Xi ..."
6,Ollama.complete,2026-06-30 17:21:58.745674+00:00,2026-06-30 17:22:02.038215+00:00,OK,80eb72ab82e62354bc7969f3776c6b51,f24dfb8fceae0636,Donald_Trump,notebook,gemma3:1b,None,None,"{""context_window"":32768,""num_output"":256,""is_c...",348.0,15.0,363.0,What is the relationship between Donald Trump ...
7,Ollama.chat,2026-06-30 17:21:58.747722+00:00,2026-06-30 17:22:02.037605+00:00,OK,80eb72ab82e62354bc7969f3776c6b51,83a8782054f0cd5c,Donald_Trump,notebook,gemma3:1b,[{'message.content': ' Given the following c...,[{'message.content': 'What is the relationship...,"{""context_window"":32768,""num_output"":256,""is_c...",348.0,15.0,363.0,assistant: What is the relationship between Do...
8,Ollama.predict,2026-06-30 17:22:02.249596+00:00,2026-06-30 17:22:48.797332+00:00,OK,80eb72ab82e62354bc7969f3776c6b51,2246b9637593ed0e,Donald_Trump,notebook,gemma3:1b,None,None,"{""context_window"":32768,""num_output"":256,""is_c...",NaN,NaN,NaN,The relationship between Donald Trump and Step...
9,Ollama.chat,2026-06-30 17:22:02.252398+00:00,2026-06-30 17:22:48.796941+00:00,OK,80eb72ab82e62354bc7969f3776c6b51,c678095ab1cf9b9e,Donald_Trump,notebook,gemma3:1b,[{'message.content': ' The following is a fr...,[{'message.content': 'The relationship between...,"{""context_window"":32768,""num_output"":256,""is_c...",4432.0,333.0,4765.0,assistant: The relationship between Donald Tru...
10,Ollama.complete,2026-06-30 17:42:52.334406+00:00,2026-06-30 17:43:05.399329+00:00,OK,fbb1d06fc54a882ed06afdf2986d9f4d,cf42ce51201509ce,Donald_Trump,chainlit,gemma3:1b,None,None,"{""context_window"":32768,""num_output"":256,""is_c...",692.0,10.0,702.0,What is the nature of their professional relat...
11,Ollama.chat,2026-06-30 17:42:53.560678+00:00,2026-06-30 17:43:03.355560+00:00,OK,fbb1d06fc54a882ed06afdf2986d9f4d,cdb37794f0a79781,Donald_Trump,chainlit,gemma3:1b,[{'message.content': ' Given the following c...,[{'message.content': 'What is the nature of th...,"{""context_window"":32768,""num_output"":256,""is_c...",692.0,10.0,702.0,assistant: What is the nature of their profess...
12,Ollama.predict,2026-06-30 17:43:05.664261+00:00,2026-06-30 17:43:49.203727+00:00,OK,fbb1d06fc54a882ed06afdf2986d9f4d,878092ec2f81cebd,Donald_Trump,chainlit,gemma3:1b,None,None,"{""context_window"":32768,""num_output"":256,""is_c...",NaN,NaN,NaN,That’s a really interesting and hotly debated ...
13,Ollama.chat,2026-06-30 17:43:05.667070+00:00,2026-06-30 17:43:47.164522+00:00,OK,fbb1d06fc54a882ed06afdf2986d9f4d,3ea62468e5100abd,Donald_Trump,chainlit,gemma3:1b,[{'message.content': ' The following is a fr...,[{'message.content': 'That’s a really interest...,"{""context_window"":32768,""num_output"":256,""is_c...",4187.0,364.0,4551.0,assistant: That’s a really interesting and hot...
14,Ollama.predict,2026-07-01 04:16:59.020617+00:00,2026-07-01 04:17:57.587769+00:00,OK,6fbae27a86ec3f22f0c08834fcdbb38b,1f202b252965fe3c,Donald_Trump,notebook,gemma3:1b,None,None,"{""context_window"":32768,""num_output"":256,""is_c...",NaN,NaN,NaN,"That’s a really perceptive question, and it’s ..."
15,Ollama.chat,2026-07-01 04:16:59.023210+00:00,2026-07-01 04:17:57.587075+00:00,OK,6fbae27a86ec3f22f0c08834fcdbb38b,5bfa86b1afc1f390,Donald_Trump,notebook,gemma3:1b,[{'message.content': ' The following is a fr...,[{'message.content': 'That’s a really percepti...,"{""context_window"":32768,""num_output"":256,""is_c...",4345.0,408.0,4753.0,assistant: That’s a really perceptive question...
16,Ollama.complete,2026-07-01 04:19:01.848463+00:00,2026-07-01 04:19:17.914235+00:00,OK,a27cc11ec7d5d43baf7292a1a7fd19a2,8c9844fa65c1bd5d,Donald_Trump,notebook,gemma3:1b,None,None,"{""context_window"":32768,""num_output"":256,""is_c...",1490.0,22.0,1512.0,"Okay, let’s focus on the question: **Did Steph..."
17,Ollama.chat,2026-07-01 04:19:01.850262+00:00,2026-07-01 04:19:17.913435+00:00,OK,a27cc11ec7d5d43baf7292a1a7fd19a2,2558ccbffeb73a84,Donald_Trump,notebook,gemma3:1b,[{'message.content': ' Given the following c...,"[{'message.content': 'Okay, let’s focus on the...","{""context_window"":32768,""num_output"":256,""is_c...",1490.0,22.0,1512.0,"assistant: Okay, let’s focus on the question: ..."
18,Ollama.predict,2026-07-01 04:19:18.113533+00:00,2026-07-01 04:20:18.222853+00:00,OK,a27cc11ec7d5d43baf7292a1a7fd19a2,5bf77bd5d3ae028b,Donald_Trump,notebook,gemma3:1b,None,None,"{""context_window"":32768,""num_output"":256,""is_c...",NaN,NaN,NaN,"Okay, let’s delve into the question of whether..."
19,Ollama.chat,2026-07-01 04:19:18.116093+00:00,2026-07-01 04:20:18.222089+00:00,OK,a27cc11ec7d5d43baf7292a1a7fd19a2,fc22ed9c961edd44,Donald_Trump,notebook,gemma3:1b,[{'message.content': ' The following is a fr...,"[{'message.content': 'Okay, let’s delve into t...","{""context_window"":32768,""num_output"":256,""is_c...",4708.0,455.0,5163.0,"assistant: Okay, let’s delve into the question..."

=== Retrieval DataFrame ===

,trace_id,span_id,retrieval_span_name,session_id,query_text,document_rank,document_score,document_content_preview,document_raw
0,12e34b0e14146ab58e9959ba8705c111,679e33520de2061d,BM25Retriever.retrieve,Donald_Trump,Did Donald Trump meet with Xi Jinping?,1,9.945602,President Donald Trump said he had made “fanta...,"{""document.score"": 9.945602417, ""document.cont..."
1,12e34b0e14146ab58e9959ba8705c111,bcf46aa47258fcc9,VectorIndexRetriever.retrieve,Donald_Trump,Did Donald Trump meet with Xi Jinping?,1,0.777383,US President Donald Trump said Wednesday he wi...,"{""document.score"": 0.7773828492, ""document.con..."
2,12e34b0e14146ab58e9959ba8705c111,7879ce79e3f32aba,HybridRetriever.retrieve,Donald_Trump,Did Donald Trump meet with Xi Jinping?,1,0.032002,Delegations from China and the United States m...,"{""document.score"": 0.0320020481, ""document.con..."
3,12e34b0e14146ab58e9959ba8705c111,679e33520de2061d,BM25Retriever.retrieve,Donald_Trump,Did Donald Trump meet with Xi Jinping?,2,9.771670,Delegations from China and the United States m...,"{""document.score"": 9.7716703415, ""document.con..."
4,12e34b0e14146ab58e9959ba8705c111,bcf46aa47258fcc9,VectorIndexRetriever.retrieve,Donald_Trump,Did Donald Trump meet with Xi Jinping?,2,0.760676,By Danny Kemp\n\nChinese President Xi Jinping ...,"{""document.score"": 0.7606758404, ""document.con..."
5,12e34b0e14146ab58e9959ba8705c111,7879ce79e3f32aba,HybridRetriever.retrieve,Donald_Trump,Did Donald Trump meet with Xi Jinping?,2,0.031778,US President Donald Trump said Wednesday he wi...,"{""document.score"": 0.031778058000000005, ""docu..."
6,12e34b0e14146ab58e9959ba8705c111,679e33520de2061d,BM25Retriever.retrieve,Donald_Trump,Did Donald Trump meet with Xi Jinping?,3,9.671169,Beijing is also likely to use Trump’s weakened...,"{""document.score"": 9.671169281000001, ""documen..."
7,12e34b0e14146ab58e9959ba8705c111,bcf46aa47258fcc9,VectorIndexRetriever.retrieve,Donald_Trump,Did Donald Trump meet with Xi Jinping?,3,0.758652,Delegations from China and the United States m...,"{""document.score"": 0.7586517352000001, ""docume..."
8,12e34b0e14146ab58e9959ba8705c111,7879ce79e3f32aba,HybridRetriever.retrieve,Donald_Trump,Did Donald Trump meet with Xi Jinping?,3,0.031778,President Donald Trump said he had made “fanta...,"{""document.score"": 0.031778058000000005, ""docu..."
9,12e34b0e14146ab58e9959ba8705c111,679e33520de2061d,BM25Retriever.retrieve,Donald_Trump,Did Donald Trump meet with Xi Jinping?,4,9.646190,US President Donald Trump heads for a superpow...,"{""document.score"": 9.6461896896, ""document.con..."
10,12e34b0e14146ab58e9959ba8705c111,bcf46aa47258fcc9,VectorIndexRetriever.retrieve,Donald_Trump,Did Donald Trump meet with Xi Jinping?,4,0.755809,US President Donald Trump heads for a superpow...,"{""document.score"": 0.7558091482, ""document.con..."
11,12e34b0e14146ab58e9959ba8705c111,7879ce79e3f32aba,HybridRetriever.retrieve,Donald_Trump,Did Donald Trump meet with Xi Jinping?,4,0.031250,US President Donald Trump heads for a superpow...,"{""document.score"": 0.03125, ""document.content""..."
12,12e34b0e14146ab58e9959ba8705c111,679e33520de2061d,BM25Retriever.retrieve,Donald_Trump,Did Donald Trump meet with Xi Jinping?,5,9.580280,US President Donald Trump said Wednesday he wi...,"{""document.score"": 9.580280304, ""document.cont..."
13,12e34b0e14146ab58e9959ba8705c111,bcf46aa47258fcc9,VectorIndexRetriever.retrieve,Donald_Trump,Did Donald Trump meet with Xi Jinping?,5,0.750133,President Donald Trump said he had made “fanta...,"{""document.score"": 0.7501326813, ""document.con..."
14,12e34b0e14146ab58e9959ba8705c111,7879ce79e3f32aba,HybridRetriever.retrieve,Donald_Trump,Did Donald Trump meet with Xi Jinping?,5,0.030077,By Danny Kemp and Beiyi Seow with Isabel Kua i...,"{""document.score"": 0.0300768883, ""document.con..."
15,12e34b0e14146ab58e9959ba8705c111,679e33520de2061d,BM25Retriever.retrieve,Donald_Trump,Did Donald Trump meet with Xi Jinping?,6,9.539506,By Danny Kemp and Beiyi Seow with Isabel Kua i...,"{""document.score"": 9.5395059586, ""document.con..."
16,12e34b0e14146ab58e9959ba8705c111,bcf46aa47258fcc9,VectorIndexRetriever.retrieve,Donald_Trump,Did Donald Trump meet with Xi Jinping?,6,0.746706,By Kang Jin-kyu and Claire Lee\n\nPresident Xi...,"{""document.score"": 0.7467057147, ""document.con..."
17,12e34b0e14146ab58e9959ba8705c111,679e33520de2061d,BM25Retriever.retrieve,Donald_Trump,Did Donald Trump meet with Xi Jinping?,7,9.463007,President Donald Trump said Monday he was read...,"{""document.score"": 9.4630069733, ""document.con..."
18,12e34b0e14146ab58e9959ba8705c111,bcf46aa47258fcc9,VectorIndexRetriever.retrieve,Donald_Trump,Did Donald Trump meet with Xi Jinping?,7,0.745230,By Danny Kemp and Beiyi Seow with Isabel Kua i...,"{""document.score"": 0.7452300943, ""document.con..."
19,12e34b0e14146ab58e9959ba8705c111,679e33520de2061d,BM25Retriever.retrieve,Donald_Trump,Did Donald Trump meet with Xi Jinping?,8,9.443912,China’s leader Xi Jinping held back-to-back ca...,"{""document.score"": 9.4439115524, ""document.con..."
20,12e34b0e14146ab58e9959ba8705c111,bcf46aa47258fcc9,VectorIndexRetriever.retrieve,Donald_Trump,Did Donald Trump meet with Xi Jinping?,8,0.743626,The leaders of North Korea and China adopted a...,"{""document.score"": 0.7436260256, ""document.con..."
21,12e34b0e14146ab58e9959ba8705c111,679e33520de2061d,BM25Retriever.retrieve,Donald_Trump,Did Donald Trump meet with Xi Jinping?,9,9.222394,Vietnam confirmed on Thursday that top leader ...,"{""document.score"": 9.2223939896, ""document.con..."
22,12e34b0e14146ab58e9959ba8705c111,bcf46aa47258fcc9,VectorIndexRetriever.retrieve,Donald_Trump,Did Donald Trump meet with Xi Jinping?,9,0.741902,President Donald Trump will visit China from M...,"{""document.score"": 0.7419020674, ""document.con..."
23,12e34b0e14146ab58e9959ba8705c111,679e33520de2061d,BM25Retriever.retrieve,Donald_Trump,Did Donald Trump meet with Xi Jinping?,10,9.028620,Beijing’s scrapping of tariffs for all but one...,"{""document.score"": 9.0286197662, ""document.con..."
24,12e34b0e14146ab58e9959ba8705c111,bcf46aa47258fcc9,VectorIndexRetriever.retrieve,Donald_Trump,Did Donald Trump meet with Xi Jinping?,10,0.737022,China’s foreign minister on Thursday urged the...,"{""document.score"": 0.7370220158, ""document.con..."
25,4b62ed0817cde49391b68aaa0f5d0d42,f1582022c73c06d9,BM25Retriever.retrieve,Donald_Trump,Did Trump possess a particular style or approa...,1,5.874861,Japanese Prime Minister Sanae Takaichi will ho...,"{""document.score"": 5.8748607635, ""document.con..."
26,4b62ed0817cde49391b68aaa0f5d0d42,3977898473ec1b6c,VectorIndexRetriever.retrieve,Donald_Trump,Did Trump possess a particular style or approa...,1,0.405991,Speaking to reporters on Friday en route to Wa...,"{""document.score"": 0.40599097510000004, ""docum..."
27,4b62ed0817cde49391b68aaa0f5d0d42,f0a51b731da36307,HybridRetriever.retrieve,Donald_Trump,Did Trump possess a particular style or approa...,1,0.016393,Speaking to reporters on Friday en route to Wa...,"{""document.score"": 0.016393442600000002, ""docu..."
28,4b62ed0817cde49391b68aaa0f5d0d42,f1582022c73c06d9,BM25Retriever.retrieve,Donald_Trump,Did Trump possess a particular style or approa...,2,5.848812,Beijing said on Monday it is in talks with Was...,"{""document.score"": 5.8488116264, ""document.con..."
29,4b62ed0817cde49391b68aaa0f5d0d42,3977898473ec1b6c,VectorIndexRetriever.retrieve,Donald_Trump,Did Trump possess a particular style or approa...,2,0.405810,Taiwan’s President Lai Ching-te said Thursday ...,"{""document.score"": 0.4058100799, ""document.con..."

Saved Phoenix evaluation CSV files to: C:\Program Files\Studying\coding\RAG_project\result\evaluation_outputs

In [4]:
# Quick inspection helper for interactive notebook work.
# After running the main Phoenix evaluation cell, this cell shows the available dataframe names.
list(phoenix_bundle.keys()) if "phoenix_bundle" in globals() else "Run Cell 4 first."

['trace_df',
 'session_spans_df',
 'span_overview_df',
 'turn_df',
 'llm_df',
 'retrieval_df']